using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

public class EntityContext : DbContext
{
    public DbSet<User> Users { get; set; }
    public DbSet<Post> Posts { get; set; }
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite($"Data Source= MyDB.db").
        LogTo(Console.WriteLine, LogLevel.Information); //check the SQL Query generated by EntityFrameworkCore

}
public class User
{
    public int Id { get; set; }
    public string? Username { get; set; }
    public string? Password { get; set; }
    public int PostId { get; set; }
    public List<Post>? Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public string? Title { get; set; }
    public string? Content { get; set; }

    // public DateTime PublishedOn { get; set; }
    public int BlogId { get; set; }
    public Blog? Blog { get; set; }
    public int UserId { get; set; }
    public User? User { get; set; }
}

public class Blog
{
    public int Id { get; set; }
    public string? Url { get; set; }
    public string? Name { get; set; }
    public int PostId { get; set; }
    public List<Post>? Posts { get; set; }
}
